### PR TITLE
PAY-761: Add revokedAt to VRP response type

### PR DESCRIPTION
**Pull request by ShahinMoneyhub**
## Description

Added revokedAt to VRP response type

### CODE REVIEW

**Comment by stefaniesatna** [comment]
Why is it WIP?

**Review by stefaniesatna — APPROVED** [review]

**Comment by stefaniesatna** [comment]
> @stefaniesatna just named it as that as I wasn't sure if that's it

I'm not either tbh 😅 might be worth waiting for Tom if you're still uncertain

**Review by tomstrat — APPROVED** [review]
Looks good to me. Have you tested to see if you get it back all correctly? I know VRP has no tests here (we should add some but another time)

**Comment by ShahinMoneyhub** [comment]
> Looks good to me. Have you tested to see if you get it back all correctly? I know VRP has no tests here (we should add some but another time)

Yeah seems to be working as normal. TBH it didn't really make a huge difference as we were getting back revokedAt originally anyways but it seems to be working as normal.

**Pull request merged**
